Repository themoment-team/K2-server, pull requests merged in 2021-07, with the labels that each got.

#175 Hotfix
  distribute-script.sh
  docker-compose-env.sh
  integrate-build-script.sh
  keystore.p12
  src/main/java/com/moment/the/table/service/TableService.java
Labels: code-review, hotfix

#177 Develop
  src/main/java/com/moment/the/table/service/TableService.java
  src/test/java/com/moment/the/controller/release/TableControllerTest.java
  src/test/java/com/moment/the/service/TableServiceTest.java
Labels: hotfix

#178 Feature/jwt refactoring
  pom.xml
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/config/mvc/ExceptionHandlerFilter.java
  src/main/java/com/moment/the/config/security/jwt/JwtRequestFilter.java
  src/main/java/com/moment/the/config/security/jwt/JwtUtil.java
Labels: code-review
