Repository themoment-team/K2-server, pull requests merged in 2021-11, with the labels that each got.

#225 Answer Create로직 리펙토링
  src/main/java/com/moment/the/answer/dto/AnswerDto.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/resources/application.yml
  src/test/java/com/moment/the/service/AnswerServiceTest.java
Labels: decision-making, clean

#228 Hotfix
  docker-compose-env.sh
  docker-compose.yml
  src/main/java/com/moment/the/admin/controller/AdminController.java
  src/main/java/com/moment/the/config/mvc/WebMvcConfigurerImpl.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: bug, urgent, clean, hotfix

#227 Feature/get request ip
  src/main/java/com/moment/the/util/HttpRequestUtils.java
  src/main/java/com/moment/the/util/controller/HttpRequestController.java
Labels: new-feature

#230 Test/get req ip
  src/test/java/com/moment/the/testConfig/AbstractControllerTest.java
  src/test/java/com/moment/the/util/HttpRequestUtilsTest.java
  src/test/java/com/moment/the/util/controller/HttpRequestControllerTest.java
Labels: build-success, new-feature
