Repository themoment-team/K2-server, pull requests merged in 2021-10, with the labels that each got.

#206 jpql -> querydsl이전 완료
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableResponseDto.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableCustomRepository.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableCustomRepositoryImpl.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
Labels: build-success, clean

#211 예상치 못한 부수 효과 떄문에 RequestResponseLoggingFilter제거
  src/main/java/com/moment/the/config/mvc/RequestResponseLoggingFilter.java
Labels: build-success, clean, hotfix

#212 Develop
  build.gradle
  src/main/java/com/moment/the/config/mvc/ExceptionHandlerFilter.java
  src/main/java/com/moment/the/config/mvc/RequestResponseLoggingFilter.java
  src/main/java/com/moment/the/config/querydsl/QuerydslConfiguration.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableResponseDto.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableCustomRepository.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableCustomRepositoryImpl.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
Labels: build-success
