Repository themoment-team/K2-server, pull requests merged in 2021-09, with the labels that each got.

#186 Swagger를 개발환경에 사용하기 위한 Config추가
  src/main/java/com/moment/the/config/swagger/SwaggerConfig.java
Labels: code-review

#187 build script를 gradle용으로 변경
  Dockerfile
  docker-compose-env.sh
Labels: code-review

#188 Hotfix
  src/main/java/com/moment/the/table/controller/TableController.java
  src/main/java/com/moment/the/table/service/TableService.java
Labels: code-review, hotfix

#189 Update gradle 빌드 툴에 따라 readme 변경
  README.md
Labels: code-review

#190 Feature/model class rename
  src/main/java/com/moment/the/answer/AnswerDomain.java
  src/main/java/com/moment/the/answer/repository/AnswerRepository.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/table/repository/TableRepository.java
  src/main/java/com/moment/the/uncomfortable/UncomfortableEntity.java
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/main/java/com/moment/the/uncomfortable/dto/AmountUncomfortableDto.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableGetDto.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableSetDto.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: code-review, hotfix

#193 Feature/rename - uncomfortable
  src/main/java/com/moment/the/uncomfortable/UncomfortableEntity.java
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: documentation, code-review

#194 Gradle 마이그레이션, Table -> Uncomfortable 마이그레이션
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  Dockerfile
  README.md
  build.gradle
  docker-compose-env.sh
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  mvnw
  mvnw.cmd
  pom.xml
  settings.gradle
  src/main/java/com/moment/the/answer/AnswerDomain.java
  src/main/java/com/moment/the/answer/repository/AnswerRepository.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/config/security/auth/MyUserDetailsService.java
  src/main/java/com/moment/the/config/security/jwt/JwtRequestFilter.java
  src/main/java/com/moment/the/config/swagger/SwaggerConfig.java
  src/main/java/com/moment/the/table/controller/TableController.java
  src/main/java/com/moment/the/table/repository/TableRepository.java
  src/main/java/com/moment/the/table/service/TableService.java
  src/main/java/com/moment/the/uncomfortable/UncomfortableEntity.java
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/main/java/com/moment/the/uncomfortable/dto/AmountUncomfortableDto.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableGetDto.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableSetDto.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: enhancement, code-review

#195 Feature/method rename - model 에 한함
  src/main/java/com/moment/the/admin/controller/AdminController.java
  src/main/java/com/moment/the/admin/service/AdminService.java
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/answer/controller/AnswerController.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/improvement/controller/ImprovementController.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
  src/test/java/com/moment/the/improvement/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/service/AdminServiceImplTest.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/java/com/moment/the/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: documentation, enhancement, code-review, hotfix

#196 Feature/rename last
  build.gradle
  src/main/java/com/moment/the/admin/controller/AdminController.java
  src/main/java/com/moment/the/admin/service/AdminService.java
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableResponseDto.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
  src/test/java/com/moment/the/service/AdminServiceImplTest.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: urgent, build-success, clean

#197 AdminDomain을 ERD에 맞게 변경했습니다.
  src/main/java/com/moment/the/admin/AdminDomain.java
  src/main/java/com/moment/the/admin/controller/AdminController.java
  src/main/java/com/moment/the/admin/dto/AdminDto.java
  src/main/java/com/moment/the/admin/dto/SignInDto.java
  src/main/java/com/moment/the/admin/repository/AdminRepository.java
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/config/security/auth/MyUserDetailsService.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/test/java/com/moment/the/improvement/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/service/AdminServiceImplTest.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/java/com/moment/the/service/ImprovementServiceTest.java
Labels: urgent, build-success, clean

#198 Erd에 맞게 AnswerDomain 변경
  src/main/java/com/moment/the/answer/AnswerDomain.java
  src/main/java/com/moment/the/answer/dto/AnswerDto.java
  src/main/java/com/moment/the/answer/dto/AnswerResDto.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
Labels: build-success, clean

#199 Erd에 맞게 ImprovementDomain 변경
  src/main/java/com/moment/the/improvement/ImprovementDomain.java
  src/main/java/com/moment/the/improvement/dto/ImprovementDto.java
  src/main/java/com/moment/the/improvement/dto/ImprovementViewAllDto.java
  src/main/java/com/moment/the/improvement/repository/ImprovementRepository.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/test/java/com/moment/the/improvement/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/service/ImprovementServiceTest.java
Labels: build-success, clean

#200 Rename Erd에 맞게 UncomfortableDomain변경
  src/main/java/com/moment/the/answer/AnswerDomain.java
  src/main/java/com/moment/the/answer/repository/AnswerRepository.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/uncomfortable/UncomfortableDomain.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableSetDto.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: build-success, clean

#201 Develop - 2021. Sep. 21
  build.gradle
  src/main/java/com/moment/the/admin/AdminDomain.java
  src/main/java/com/moment/the/admin/controller/AdminController.java
  src/main/java/com/moment/the/admin/dto/AdminDto.java
  src/main/java/com/moment/the/admin/dto/SignInDto.java
  src/main/java/com/moment/the/admin/repository/AdminRepository.java
  src/main/java/com/moment/the/admin/service/AdminService.java
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/answer/AnswerDomain.java
  src/main/java/com/moment/the/answer/controller/AnswerController.java
  src/main/java/com/moment/the/answer/dto/AnswerDto.java
  src/main/java/com/moment/the/answer/dto/AnswerResDto.java
  src/main/java/com/moment/the/answer/repository/AnswerRepository.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/config/security/auth/MyUserDetailsService.java
  src/main/java/com/moment/the/config/swagger/SwaggerConfig.java
  src/main/java/com/moment/the/improvement/ImprovementDomain.java
  src/main/java/com/moment/the/improvement/controller/ImprovementController.java
  src/main/java/com/moment/the/improvement/dto/ImprovementDto.java
  src/main/java/com/moment/the/improvement/dto/ImprovementViewAllDto.java
  src/main/java/com/moment/the/improvement/repository/ImprovementRepository.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/main/java/com/moment/the/uncomfortable/UncomfortableDomain.java
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableResponseDto.java
  src/main/java/com/moment/the/uncomfortable/dto/UncomfortableSetDto.java
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
  src/test/java/com/moment/the/improvement/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/service/AdminServiceImplTest.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/java/com/moment/the/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: build-success, clean

#202 Update localhost origin allow
  src/main/java/com/moment/the/config/mvc/WebMvcConfigurerImpl.java
Labels: clean, hotfix

#203 filter에서 처리하는 ExceptionHandler리펙토링
  src/main/java/com/moment/the/config/mvc/ExceptionHandlerFilter.java
Labels: build-success, clean

#204 querydsl configuration
  build.gradle
  src/main/java/com/moment/the/config/querydsl/QuerydslConfiguration.java
Labels: build-success

#207 [hotfix] could not connect redis exception
  docker-compose.yml
Labels: bug, urgent, hotfix

#205 UncomfortableService.getNumberOfUncomfortable에서 사용하던 amountUncomfortable()를 count()로 변경
  src/main/java/com/moment/the/uncomfortable/repository/UncomfortableRepository.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
Labels: build-success, clean

#209 hotfix Service 'app' has a link to service 'db:redis' which is undefined
  docker-compose-env.sh
  docker-compose.yml
  src/main/java/com/moment/the/admin/controller/AdminController.java
  src/main/resources/application.yml
Labels: bug, hotfix

#210 Fix http status가 항상 200를 logging하는 문제 해결
  src/main/java/com/moment/the/config/mvc/RequestResponseLoggingFilter.java
Labels: build-success, clean
