Repository themoment-team/K2-server, pull requests merged in 2021-12, with the labels that each got.

#231 AnswerService리팩터링
  src/main/java/com/moment/the/answer/repository/AnswerCustomRepository.java
  src/main/java/com/moment/the/answer/repository/AnswerCustomRepositoryImpl.java
  src/main/java/com/moment/the/answer/repository/AnswerRepository.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
Labels: build-success, clean

#236 Feature/change http method
  .github/workflows/gradle.yml
  .gitignore
  README.md
  docker-compose-env.sh
  gradlew.bat
  src/main/java/com/moment/the/exceptionAdvice/exception/AccessTokenExpiredException.java
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
Labels: build success, clean

#237 Update 좋아요 증가/감소 API URI
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/test/java/com/moment/the/controller/release/UncomfortableControllerTest.java
Labels: build success, clean, hotfix

#240 Hotfix
  docker-compose-env.sh
  docker-compose.yml
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: bug, build success, clean, hotfix

#241 Hotfix
  src/main/java/com/moment/the/exception/ErrorCode.java
  src/main/java/com/moment/the/exception/ErrorResponse.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
Labels: urgent, build success, clean, hotfix

#242 fix AccessNotFoundException
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/exception/ErrorCode.java
  src/main/java/com/moment/the/exception/exceptionCollection/AccessNotFoundException.java
  src/main/java/com/moment/the/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
Labels: build success, legacy, clean

#243 refresh token 기능제거
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/config/security/jwt/JwtRequestFilter.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: build success, clean

#245 Hotfix
  Dockerfile
  README.md
  docker-compose-env.sh
  docker-compose.yml
  prod-build.sh
Labels: build success, hotfix

#244 Fix/exception jeayoung
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/config/security/jwt/JwtRequestFilter.java
  src/main/java/com/moment/the/exception/exceptionCollection/NoCommentException.java
  src/main/java/com/moment/the/exception/exceptionCollection/NoPostException.java
  src/main/java/com/moment/the/exception/exceptionCollection/UserNotFoundException.java
  src/main/java/com/moment/the/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/service/AdminServiceImplTest.java
Labels: build success, legacy

#247 fix 잘못된 로그
  src/main/java/com/moment/the/exception/handler/GlobalExceptionHandler.java
Labels: build success, clean

#248 Fix/exception sijun
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/java/com/moment/the/config/security/jwt/JwtRequestFilter.java
  src/main/java/com/moment/the/exception/exceptionCollection/AccessTokenExpiredException.java
  src/main/java/com/moment/the/exception/exceptionCollection/AnswerAlreadyExistsException.java
  src/main/java/com/moment/the/exception/exceptionCollection/InvalidTokenException.java
  src/main/java/com/moment/the/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
Labels: clean

#250 Testing a S3 upload
  .github/workflows/gradle.yml
Labels: urgent

#260 Remove MessageConfiguration
  src/main/java/com/moment/the/config/exception/MessageConfiguration.java
Labels: build success, clean

#262 Feature/refactoring uncomfortable service
  src/main/java/com/moment/the/uncomfortable/controller/UncomfortableController.java
  src/main/java/com/moment/the/uncomfortable/service/UncomfortableService.java
  src/test/java/com/moment/the/service/UncomfortableServiceTest.java
Labels: build success, decision making, clean

#261 Feature/refactoring answer service
  src/main/java/com/moment/the/answer/dto/AnswerDto.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/test/java/com/moment/the/service/AnswerServiceTest.java
Labels: build success, clean

#263 Feature/modelmapper migration
  build.gradle
  src/main/java/com/moment/the/admin/service/AdminServiceImpl.java
  src/main/java/com/moment/the/improvement/ImprovementDomain.java
  src/main/java/com/moment/the/improvement/controller/ImprovementController.java
  src/main/java/com/moment/the/improvement/dto/ImprovementDto.java
  src/main/java/com/moment/the/improvement/dto/ImprovementViewAllDto.java
  src/main/java/com/moment/the/improvement/repository/ImprovementCustomRepository.java
  src/main/java/com/moment/the/improvement/repository/ImprovementCustomRepositoryImpl.java
  src/main/java/com/moment/the/improvement/repository/ImprovementRepository.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/test/java/com/moment/the/improvement/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/service/AdminServiceImplTest.java
  src/test/java/com/moment/the/service/ImprovementServiceTest.java
Labels: build success, decision making, clean

#265 Feature/util [현재 회원 엔티티, 이메일 가져오기]
  build.gradle
  src/main/java/com/moment/the/util/AppUtil.java
  src/test/java/com/moment/the/testConfig/AdminTestUtil.java
  src/test/java/com/moment/the/util/AppUtilTest.java
Labels: urgent, build success, new feature, decision making, clean, hotfix

#266 Feature/query-performance [답변]
  src/main/java/com/moment/the/admin/AdminDomain.java
  src/main/java/com/moment/the/answer/controller/AnswerController.java
  src/main/java/com/moment/the/answer/dto/AnswerResponseDto.java
  src/main/java/com/moment/the/answer/repository/AnswerCustomRepository.java
  src/main/java/com/moment/the/answer/repository/AnswerCustomRepositoryImpl.java
  src/main/java/com/moment/the/answer/service/AnswerService.java
  src/main/resources/application-dev.yml
  src/test/java/com/moment/the/service/AnswerServiceTest.java
  src/test/resources/application.yml
Labels: build success, clean

#267 Fix/improvement
  src/main/java/com/moment/the/improvement/controller/ImprovementController.java
  src/main/java/com/moment/the/improvement/dto/ImprovementDto.java
  src/main/java/com/moment/the/improvement/repository/ImprovementCustomRepository.java
  src/main/java/com/moment/the/improvement/repository/ImprovementCustomRepositoryImpl.java
  src/main/java/com/moment/the/improvement/service/ImprovementService.java
  src/test/java/com/moment/the/service/ImprovementServiceTest.java
  src/test/java/com/moment/the/testConfig/AdminTestUtil.java
  src/test/java/com/moment/the/util/AppUtilTest.java
Labels: build success, clean, hotfix
