Repository themoment-team/K2-server, pull requests merged in 2022-01, with the labels that each got.

#269 Feature/valid-exception
  src/main/java/com/moment/the/admin/dto/AdminDto.java
  src/main/java/com/moment/the/exception/ErrorCode.java
  src/main/java/com/moment/the/exception/ErrorResponse.java
  src/main/java/com/moment/the/exception/handler/GlobalExceptionHandler.java
Labels: build success, new feature

#276 Fix profile test
  Dockerfile
  docker-test-container-execute.sh
  prod-build.sh
  src/main/java/com/moment/the/config/swagger/SwaggerConfig.java
  src/main/resources/application-test.yml
Labels: bug, decision making

#280 WorkFlow 파일 버전 재업로드
  .github/workflows/gradle.yml
Labels: hotfix

#281 Add pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new feature, decision making
